Add disclaimer about matrix batch effects (#18)
HumanCellAtlas/dcp2 pull request #19
Opened 2021-04-29 00:36 UTC by hannes-ucsc

2021-04-29 03:06 UTC, NoopDog requested changes
Hi there, nice to see this moving forward. One comment, with the warning text in the project-level matrices paragraph, it seems to imply that the contributor-generated matrices are not normalized. Some may well be as far as I understand it.  We place no restrictions on contributor-generated matrices. Since they may be representing the result from a paper they may be highly normalized, filtered, tweaked, etc. to get the pretty picture. 

One suggestion to fix this is to, in the first paragraph, state there are three kinds of matrix files DCP/1-generated, DCP/2-generated, and contributor-generated, and that the DCP1 and DCP2-generated matrices are not normalized "within or across projects", and the contributor-generated matrices are whatever the contributor gave.

2021-04-29 08:18 UTC, clairerye commented
100% agree with Dave's comment above, I don't think we should have a blanket statement. Can we use the metadata to distinguish if the statement should apply, or as Dave suggests a statement that covers the fact that CGMs are likely to be batch corrected etc?

2021-04-29 12:49 UTC, aherbst-broad approved these changes

2021-04-29 13:46 UTC, hannes-ucsc commented
@clairerye, from your agreement with @NoopDog it appears that you also intended to request changes. Could you please use the Github reject/approve functionality to make your choice explicit?

2021-04-29 13:55 UTC, hannes-ucsc commented
@NoopDog 

> Hi there, nice to see this moving forward. One comment, with the warning text in the project-level matrices paragraph, it seems to imply that the contributor-generated matrices are not normalized. 

It states that the CGMs are 1) not corrected for batch effects and 2) not normalized *across* (!) projects.

I think it is safe to assume that 2 is the case because why would a contributor normalize against other HCA projects? If we get a pan-project matrix we need to invent a new category for those. Note the definition of *project-level* matrix at the beginning of the modified section.

Please explain why you think 1) does not apply.

> One suggestion to fix this is to, in the first paragraph, state there are three kinds of matrix files DCP/1-generated, DCP/2-generated, and contributor-generated, and that the DCP1 and DCP2-generated matrices are not normalized "within or across projects", and the contributor-generated matrices are whatever the contributor gave.

That would be scope creep. I will make clear in the issue that this PR only addresses a disclaimer about CGMs.

2021-04-29 14:58 UTC, clairerye commented
If it is just about the CGMs then could we simply state that the DCP takes not responsibility for what, if any, batch correction or normalisation techniques have been used as they have been done directly by the contributor?

2021-04-29 15:10 UTC, hannes-ucsc commented
That works for me. Do you want to suggest the specific wording using the suggest changes feature?

2021-04-29 15:21 UTC, clairerye commented on docs/dcp2_system_design.rst
> +contributors may provide along with the actual matrices. These matrices should
DCP takes no responsibility for what, if any, batch correction or normalisation techniques have been used as they have been done directly by the data contributor.

2021-04-29 15:29 UTC, clairerye requested changes
suggested language changes

2021-04-29 15:29 UTC, clairerye commented on docs/dcp2_system_design.rst
> +be interpreted with caution: the data is not corrected for batch effects nor
Suggested text: DCP takes no responsibility for what, if any, batch correction or normalisation techniques have been used as they have been done directly by the data contributor.

2021-04-29 16:47 UTC, clairerye commented
oh no, did I actually comit the text change instead of just making the suggestion?

2021-04-29 17:20 UTC, hannes-ucsc commented
No problem, I can revert the commit.

2021-04-30 00:18 UTC, NoopDog requested changes
Hmm, I thought the intent was to inform that DCP-generated matrices are not normalized within or across projects and that the DCP makes no representations about the normalization status of the contributor-generated matrices. This text only comments on the contributor-generated matrices and seems to leave out discussing the DCP-generated matrices.

2021-04-30 00:45 UTC, hannes-ucsc commented
@clairerye I used your wording.

@NoopDog, maybe we can avoid blowing this up into something it wasn't intended to be?  Open a ticket and/or PR if you want more text to be added. Baby steps. Thank you!

2021-04-30 17:42 UTC, NoopDog approved these changes

2021-04-30 18:16 UTC, ruchim approved these changes
LGTM!

2021-05-04 12:06 UTC, clairerye approved these changes

2021-05-04 12:08 UTC, clairerye commented
> Hmm, I thought the intent was to inform that DCP-generated matrices are not normalized within or across projects and that the DCP makes no representations about the normalization status of the contributor-generated matrices. This text only comments on the contributor-generated matrices and seems to leave out discussing the DCP-generated matrices.

I think given the title of the PR this was just about CGMs. I am assuming we will have a different disclaimer for the DCP matrices.

2021-05-11 15:06 UTC, kbergin approved these changes

2021-06-16 17:29 UTC, merged