Allow for TDR dataset per HCA project
HumanCellAtlas/dcp2 pull request #38
Opened 2021-08-24 22:48 UTC by hannes-ucsc

#37

2021-08-25 12:51 UTC, aherbst-broad approved these changes
Tested the regexes, looks good.

2021-08-25 17:06 UTC, NoopDog approved these changes

2021-08-25 17:12 UTC, ESapenaVentura requested changes
Tested some regexes and left some comments!

2021-08-25 17:12 UTC, ESapenaVentura commented on docs/dcp2_system_design.rst
> +    dataset_name = "hca_" , deployment , "_", [project_id], "__" , creation_date , ["_" , qualifier]
Just a small suggestion:

```suggestion
    dataset_name = "hca_" , deployment , "_" , [project_id] , "__" , creation_date , ["_" , qualifier]
```

And I have a question, are we keeping the underscore in `hca_` because it will be static for all dataset names?

2021-08-25 17:12 UTC, ESapenaVentura commented on docs/dcp2_system_design.rst
> +    _(\d{4})(\d{2})(\d{2})
```suggestion
    (?:_(\d{4})(\d{2})(\d{2})
```

2021-08-25 17:12 UTC, ESapenaVentura commented on docs/dcp2_system_design.rst
> +    )?
I think we want the `$` at the very end of the regex:
```suggestion
    (?:_([a-zA-Z][a-zA-Z0-9]{0,15}))?
    )?$
```
If not, for example, `hca_staging_9654e4314c0148d5a79f1c5439659da3__20200812_a123456789012345_20200814_a123456789012345 ` (With a space at the end of the string) will cause that everything but the last non-capturing group is matched to the regex, whereas with the `$` at the end it invalidates the whole match if there's any char at the end

2021-08-25 17:35 UTC, hannes-ucsc commented on docs/dcp2_system_design.rst
> +    _(\d{4})(\d{2})(\d{2})
I'd rather keep it this way so that the nesting is more clear and so that there is correspondence between the lines in the three literal blocks.

2021-08-25 17:37 UTC, hannes-ucsc commented on docs/dcp2_system_design.rst
> +    )?
Good catch. That's a big bug.

2021-08-25 17:47 UTC, hannes-ucsc commented on docs/dcp2_system_design.rst
> +    dataset_name = "hca_" , deployment , "_", [project_id], "__" , creation_date , ["_" , qualifier]
Yes, all HCA snapshot and dataset names must start with `hca_` so they are distinct from any non-HCA snapshots and datasets in the TDR instance. An alternative, equivalent grammar would be 

```suggestion
    dataset_name = "hca" , "_" , deployment , "_", [project_id], "__" , creation_date , ["_" , qualifier]
```

but I don't see the point in splitting one terminal into two.

2021-08-25 17:47 UTC, hannes-ucsc commented on docs/dcp2_system_design.rst
> +    dataset_name = "hca_" , deployment , "_", [project_id], "__" , creation_date , ["_" , qualifier]
Fixed (the spaces).

2021-08-25 17:47 UTC, hannes-ucsc commented on docs/dcp2_system_design.rst
> +    )?
Fixed. Also moved the anchors to a separate line.

2021-08-26 09:18 UTC, ESapenaVentura commented on docs/dcp2_system_design.rst
> +    _(\d{4})(\d{2})(\d{2})
Oh, I get it now - Thanks, didn't notice the pattern

2021-08-26 09:19 UTC, ESapenaVentura approved these changes
LGTM 👍

2021-08-27 17:51 UTC, ruchim reviewed
Looks good to me!

2021-08-27 17:51 UTC, ruchim commented on docs/dcp2_system_design.rst
> +    dataset_name = "hca_" , deployment , "_" , [project_id] , "__" , creation_date , ["_" , qualifier]
given project id length -- are dataset names still long enough? concerns about the character limit?

2021-08-27 17:51 UTC, ruchim commented on docs/dcp2_system_design.rst
> +    dataset_name = "hca_" , deployment , "_" , [project_id] , "__" , creation_date , ["_" , qualifier]
answered below

2021-08-31 15:10 UTC, nikellepetrillo approved these changes

2021-08-31 17:28 UTC, hannes-ucsc commented
@ruchi can you formally approve? You left a comment implying approval but I don't have a green check mark:

![image](https://user-images.githubusercontent.com/5143256/131548759-a3389251-20ae-466c-a700-094dd08f5557.png)

2021-09-02 17:28 UTC, NoopDog approved these changes

2021-09-02 17:51 UTC, hannes-ucsc commented
@kbergin delegated review to @nikellepetrillo

https://humancellatlas.slack.com/archives/C01360XN04S/p1630603744034100?thread_ts=1630603357.033400&cid=C01360XN04S

2021-09-02 17:51 UTC, nikellepetrillo approved these changes

2021-09-02 19:31 UTC, ruchim approved these changes
checked the latest commit, regex updates look good

2021-09-03 14:15 UTC, aherbst-broad approved these changes

2021-09-10 21:24 UTC, merged