Fix: Submitter ID for Lungmap is based on wrong slug (#35)
HumanCellAtlas/dcp2 pull request #44
Opened 2021-09-27 20:44 UTC by danielsotirhos

2021-09-30 01:10 UTC, hannes-ucsc requested changes
Can you motivate the change a little bit in the body of the commit message?

And then copy what you wrote to the PR description.

This will make it easier for the reviewers. We have to go through formal review according to SOP.

2021-10-04 01:08 UTC, hannes-ucsc approved these changes

2021-10-04 10:43 UTC, ESapenaVentura approved these changes
LGTM 👍

2021-10-04 14:47 UTC, kbergin approved these changes

2021-10-05 12:07 UTC, amnonkhen commented
LGTM

2021-10-05 12:08 UTC, amnonkhen approved these changes

2021-10-05 13:47 UTC, aherbst-broad approved these changes

2021-10-07 16:24 UTC, NoopDog approved these changes

2021-12-01 23:17 UTC, merged