designated reviewers of test data as codeowners
HumanCellAtlas/dcp2 pull request #65
Opened 2022-09-05 11:24 UTC by amnonkhen

2022-09-06 12:58 UTC, ncalvanese1 approved these changes

2022-09-07 18:02 UTC, hannes-ucsc requested changes
The SOP must remain self-contained, especially when it comes to a central aspect like the list of designated reviewers. And even if outsourcing that list was an option, it would be hazardous to leave a potentially conflicting list in the SOP. I'll reject any change that moves the list outside of this repository or that creates a duplicate of the list. 

Consider creating a `CODEOWNERS` in this repository, linking to or embedding that file in the SOP `.rst` and having the `CODEOWNERS` file in the `schema-test-data` repository be a symlink to the file in a submodule referring to this repository.

Furthermore, the SOP must be followed which includes sending Slack notifications to the reviewers. I don't think this was done for this PR.

2022-09-07 18:02 UTC, hannes-ucsc commented on docs/dcp2_operating_procedures.rst
> +The list of reviewrs in maintained as the `CODEOWNERS`_ list of the `schema-test-data`_ repo.
```suggestion
The list of reviewers is maintained as the `CODEOWNERS`_ list of the `schema-test-data`_ repo.
```

2022-10-14 01:28 UTC, hannes-ucsc commented
Closing due to lack of activity.

2022-10-14 01:28 UTC, closed without merging